// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-kvLLw877kHaDVGSoE-kN3zoZiihLpaI',
    appId: '1:400538727180:web:b73fe1f0c9d394cf26cf29',
    messagingSenderId: '400538727180',
    projectId: 'chatapp-e52e9',
    authDomain: 'chatapp-e52e9.firebaseapp.com',
    storageBucket: 'chatapp-e52e9.firebasestorage.app',
    measurementId: 'G-3KH9872M13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6DloiRA6WkPGL1o0RZOfzoxU95y5rmoo',
    appId: '1:400538727180:android:46520b8bc7706be326cf29',
    messagingSenderId: '400538727180',
    projectId: 'chatapp-e52e9',
    storageBucket: 'chatapp-e52e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChASB_han7W3-fpN6wq2SKyegp5D74MlY',
    appId: '1:400538727180:ios:32c984dd145ba0c626cf29',
    messagingSenderId: '400538727180',
    projectId: 'chatapp-e52e9',
    storageBucket: 'chatapp-e52e9.firebasestorage.app',
    iosBundleId: 'com.example.chatterUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChASB_han7W3-fpN6wq2SKyegp5D74MlY',
    appId: '1:400538727180:ios:32c984dd145ba0c626cf29',
    messagingSenderId: '400538727180',
    projectId: 'chatapp-e52e9',
    storageBucket: 'chatapp-e52e9.firebasestorage.app',
    iosBundleId: 'com.example.chatterUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-kvLLw877kHaDVGSoE-kN3zoZiihLpaI',
    appId: '1:400538727180:web:b4f9d115bd10bdc726cf29',
    messagingSenderId: '400538727180',
    projectId: 'chatapp-e52e9',
    authDomain: 'chatapp-e52e9.firebaseapp.com',
    storageBucket: 'chatapp-e52e9.firebasestorage.app',
    measurementId: 'G-LM7R1Y8HSC',
  );

}